name: ktlint

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    kotlin:
        name: runner / suggester / spotless
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: ./.github/actions/setup-build-env
            - run: git fetch origin main
            - run: ./gradlew spotlessKotlinApply
            - uses: reviewdog/action-suggester@2558ba17e65a9039e73764a73009fc05fef28a46 # v1.24.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  tool_name: spotless
            - run: ./gradlew spotlessKotlinCheck
