name: ktlint

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    kotlin:
        name: runner / suggester / spotless
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: ./.github/actions/setup-build-env
            - run: git fetch origin main
            - run: ./gradlew spotlessKotlinApply
            - uses: reviewdog/action-suggester@4553543bea739d9d503379d786148cfd561de5fa # v1.25.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  tool_name: spotless
            - run: ./gradlew spotlessKotlinCheck
